
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  socket: /tmp/mysql.sock
  password: ""

development:
  <<: *default
  database: chemis_dev
  
test:
  <<: *default
  database: chemis_test
